### ISSUE TITLE
[feature request] 請問可否支援繁體中文搜尋？

### ISSUE THREAD

**Issue by cajinz** [lazyloong/obsidian-fuzzy-chinese#1]
感謝好用的插件。不知道有無可能一樣透過全拼或首字母，一併搜尋到繁體中文？
例如輸入bz可以同時找到 本質 及 本质。

**Comment by lazyloong** [comment]
1.5.0版本添加加了繁体支持，实际上是先转换为简体再通过原来的方法搜索的

![image](https://user-images.githubusercontent.com/54649691/230765602-d987bbac-31b7-4cba-abaa-f53dc5719c86.png)
