### ISSUE TITLE
提示更新 2.2.1，实际上不存在，导致更新报错

### ISSUE THREAD

**Issue by quanru** [lazyloong/obsidian-fuzzy-chinese#10]
![image](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/11739753/7930299d-4517-44cf-b2bc-0e77a1fffa29)
![image](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/11739753/7b4110b5-138a-4315-893f-97374260fa83)

**Comment by lazyloong** [comment]
抱歉抱歉，我忘记放新版本上去了😂

**Comment by quanru** [comment]
https://github.com/quanru/obsidian-periodic-para/blob/main/.github/workflows/release.yml
可以参考这个，只要打 tag，就会自己上传 release

**Comment by lazyloong** [comment]
谢谢你的建议，我暑假开始的时候就想着设置一个Actions了，但是一直懒得搞🙈

**Comment by lazyloong** [comment]
哇趣，多谢你的建议，搞了这个之后确实方便多了
