### ISSUE TITLE
[FR]: tag建议

### ISSUE THREAD

**Issue by architaktus** [lazyloong/obsidian-fuzzy-chinese#18]
类似双链建议，**输入#时**是否也能如双链输入[[般支持中文拼音检索？

感谢！

**Comment by lazyloong** [comment]
OK了，请尝试2.7.0版，在设置里打开

**Comment by architaktus** [comment]
感谢更新！
* 新发现的小bug是：zh会搜到sh的结果，譬如“术语”会被shu和zhu搜索到

**Comment by lazyloong** [comment]
感谢你的反馈，但这不是bug，术确实有zhu这个读音，如白术。想解决也不是没有办法，比如增加常见词语的拼音表，但是会很麻烦，所以没有必要这样做。
![image](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/54649691/7b9eb68c-aa47-4c72-b472-be5ff351f134)

**Comment by lazyloong** [comment]
类似的，我刚发现b竟然能匹配“体”
![image](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/54649691/436efaa9-adaa-40ae-a94f-a3864c4e0e91)

**Comment by architaktus** [comment]
wow 没有用的新知识增加了！


> 增加常见词语的拼音表

没关系，目前的检索方式已经很实用了，感恩！
