### ISSUE TITLE
Obsidian强退后再打开，插件需要重新启用才能正常搜索

### ISSUE THREAD

**Issue by YandLiu** [lazyloong/obsidian-fuzzy-chinese#21]
最近电脑蓝屏比较多，蓝屏后打开Obsidian会发现插件并没有起作用，搜索列表里没有任何文件，得重新启用才能恢复正常

**Comment by lazyloong** [comment]
这个问题有点奇怪啊。如果你再次发现插件没有起作用请按 ctrl shift i 打开开发者工具看看有没有加载索引的信息
![image](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/54649691/4a2433cb-539e-480f-9112-78eb95ebbe15)

**Comment by YandLiu** [comment]
试了下直接结束掉Obsidian进程，可以复现
>Fuzzy Chinese Pinyin: command indexing completed, totaling 143 items, taking 0.153s
>Fuzzy Chinese Pinyin: tag indexing completed, totaling 0 items, taking 0s
![image](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/26127104/354ca8fa-090e-48bc-bcd7-51132fede864)


重新启用插件后恢复正常
![image](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/26127104/6ab4642f-a67c-4662-9d45-a06482eaf25e)

**Comment by lazyloong** [comment]
尝试一下2.7.2版，这个问题应该没有了
