### ISSUE TITLE
【建议】文档属性中 tags 希望能拼音补全

### ISSUE THREAD

**Issue by hotoo** [lazyloong/obsidian-fuzzy-chinese#25]
<table>
<tr>
  <th>拼音无补全</th>
  <th>汉字有补全</th>
  <th>源码模式无补全</th>
</tr>
<tr>
  <td>
<img src="https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/143572/42369692-cb10-4eb1-a0fe-67c53f33fdeb" />
</td><td>

<img src="https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/143572/c6581b8e-c3e9-4b52-84fe-591c172b676b" />
</td><td>

<img src="https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/143572/00bce378-8c54-4fff-b08e-88cd565f3573" />
</td></tr>

<tr>
  <td>期望拼音可补全</td>
  <td>符合预期</td>
  <td>可接受不补全，最好能补全</td>
</tr>
</table>

**Comment by lazyloong** [comment]
我翻了好久，ob根本没有暴露这个建议功能的接口，我硬将整个建议功能换了一遍。现在应该可以了，2.16.0版😵‍💫。

**Comment by hotoo** [comment]
![image](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/143572/9cac7beb-97f2-46c9-903f-52e4753db36d)

跟之前没什么区别，是要怎么激活吗？

**Comment by lazyloong** [comment]
![image](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/54649691/37448a5a-faf7-48a7-aadc-5ff3d316fd0c)

这玩意是自动打开的，没加设置。有更新吗，更新打开插件之后要关闭当前已有的页面，重新打开才生效

**Comment by hotoo** [comment]
> 这玩意是自动打开的，没加设置。有更新吗，更新打开插件之后要关闭当前已有的页面，重新打开才生效

插件和 Obsidian 都是最新的；重启过 Obsidan，也重启过插件，都没有自动补全

**Comment by lazyloong** [comment]
这就怪了，你看看这个页面中间两个功能有没有被替换成插件的功能，它和标签补全应该是一起加进来的
![image](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/54649691/976f9c31-3517-4dbf-8590-5efe3f1fd4dc)

**Comment by lazyloong** [comment]
@hotoo 你现在看看有没有问题了

**Comment by hotoo** [comment]
Reading view 可以了。源码列表模式下不支持，但是不影响，够用了，赞的👍🏻
