### ISSUE TITLE
[FR]：拼音搜索忽视大小写

### ISSUE THREAD

**Issue by hustrjh** [lazyloong/obsidian-fuzzy-chinese#26]
感谢作者分享这么棒的插件！谢谢！❤️
这个插件只有在小写字母时才进行拼音搜索，请问是否可以设置忽视大小写进行拼音搜索？希望提供这样的设置选项，这将增加许多便利，谢谢！

**Comment by hustrjh** [comment]
因为OB里一般大小写不敏感，所以有些不习惯~十分感谢！

**Comment by lazyloong** [comment]
OK，加完了

**Comment by hustrjh** [comment]
太棒啦！👍👍👍
不过更新简介中没有提到修改了这个功能，部分原先习惯自动大小写的用户可能会不适应~
![image](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/69783980/723b1eb0-784b-4c40-8603-26c27f031d66)

**Comment by lazyloong** [comment]
怪事，我明明写的默认打开

**Comment by lazyloong** [comment]
我重新安装了一遍，是默认打开的，所以没啥关系
