### ISSUE TITLE
[FR]：搜索文件时默认显示文件数量可以自定义

### ISSUE THREAD

**Issue by hustrjh** [lazyloong/obsidian-fuzzy-chinese#27]
搜索文件时默认显示的文件相当于显示最近打开的文件，希望可以自定义（或者增加）显示的文件数量，这样方便快速打开先前打开的文件，谢谢！❤️

**Comment by hustrjh** [comment]
额，不知道为什么我只有7个。🤔
![image](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/69783980/1a14aa46-06a7-4783-b407-fe7e49d094f2)

**Comment by lazyloong** [comment]
有时候这个列表会莫名清空，你多浏览一些就有最多10个了

**Comment by lazyloong** [comment]
反正插件里历史只有7个，你去原生切换那里看肯定也是7个

**Comment by hustrjh** [comment]
测试了下，貌似要把这几个选项都开启才行，否则部分历史记录会被筛掉。感谢！🤝
![image](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/69783980/411f8ef7-623e-4137-ae0d-968055c06367)

**Comment by lazyloong** [comment]
好吧，原来是这个原因，我还以为是历史偶尔清空呢，我的就会这样
