### ISSUE TITLE
可以增加是显示文件类型的开关吗？我不想显示.md

### ISSUE THREAD

**Issue by FEI352** [lazyloong/obsidian-fuzzy-chinese#29]
主要是我库里的文件都是.md，看这个后缀也没有意义啊。

**Comment by lazyloong** [comment]
🤔，请问你哪里比较多显示.md
![image](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/54649691/18e69d72-9ed8-4ca5-b39b-40dcac026fc6)

**Comment by FEI352** [comment]
> 🤔，请问你哪里比较多显示.md ![image](https://private-user-images.githubusercontent.com/54649691/289269633-18e69d72-9ed8-4ca5-b39b-40dcac026fc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMjM2MzIsIm5iZiI6MTcwMjEyMzMzMiwicGF0aCI6Ii81NDY0OTY5MS8yODkyNjk2MzMtMThlNjlkNzItOWVkOC00Y2E1LWIzOWItNDBkY2FjMDI2ZmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDEyMDIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5ZjdhZDNjZTVjNDhhOGUyZTFkYWNjNWJhNWNlODc4M2RlMWFmYzhlOGU4NjgzNzVjMmY2ZDA3YjUzYzI5ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.di0D3pz0vnkPicGPLdwJ-BNc3jJPuhvEWTlSsKDLZJ8)

奇怪，为什么我的界面和你的不一样，不过我这个库也只有你一个插件啊，主题也是默认的。我这里显示是这样的。
![这样的](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/104716040/13bbeed7-f9f9-4c6e-81e1-d30069735591)

**Comment by lazyloong** [comment]
噢，我知道了，你去看看设置的历史记录是不是“使用完整路径”，可以调成只用文件名的

**Comment by lazyloong** [comment]
就算是没调，你随便输入一点东西搜索也是我那张图的样子嘛

**Comment by FEI352** [comment]
> 噢，我知道了，你去看看设置的历史记录是不是“使用完整路径”，可以调成只用文件名的

谢谢你，照你所做的，正常了。

**Comment by lazyloong** [comment]
你这还算好的，文件夹一深简直没法看（“使用完整路径”和原生搜索都是这样）
![image](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/54649691/194f4aac-5bc5-4d0e-b7aa-d6306b6a1165)
