### ISSUE TITLE
文档多的时候速度太慢

### ISSUE THREAD

**Issue by eryajf** [lazyloong/obsidian-fuzzy-chinese#3]
很早就期待这样的插件，目测这个插件后期会被官方内置。

我这边目前有文档两千多篇，然后检索的时候，卡顿太严重了，不知道这个有没有比较好的解决方案。

**Comment by lazyloong** [comment]
主要是对于那么多笔记名字一一进行拼音查询，计算量实在是太大了，也没有找到什么有效的优化方法。我自己3000笔记用得还是蛮顺畅的（i7的cpu），不过既然发布到官方插件库里了肯定还是要尝试去优化一下速度的(╥╯﹏╰╥)ง。

**Comment by lazyloong** [comment]
@eryajf 重新实现了查询算法，速度应该加快了很多，现在试试2.0.0版本的速度怎么样

**Comment by eryajf** [comment]
太强了，已经试了，超级6，现在速度太快啦
