### ISSUE TITLE
[建议] 搜索排序优化

### ISSUE THREAD

**Issue by Newdea** [lazyloong/obsidian-fuzzy-chinese#30]
这个插件越来越好用了，感谢作者的贡献。

用的过程中，在打开文件或移动到文件夹时，输入关键词后，给出的搜索建议排序，有时要向下翻些才能找到想要的，建议能按最近使用、原关键词、最短路径、最后才是模糊匹配的顺序显示。

解释下，
原关键词指原本路径中就含有的，如打开`obs`,给出的搜索建议中
```
obsidian（原关键词）
o,but,this (也算是原关键词？)
哦不是（模糊匹配）
```

希望意思表达清了😄️

以上，祝好

**Comment by lazyloong** [comment]
谢谢你的建议，我这排序算法确实有点不尽人意，不过我有点奇怪，你给的示例是搜索出来的顺序吗。

我是按照覆盖率（匹配的文本占总文本的比例），分割的数量（一整块匹配比分散的分数更高）和位置（匹配文本在总文本中靠前一点的分更高），所以正常排序应该是哦不是、obsidian和o,but,this。

原关键词加分确实可以，但是最短路径是什么意思呢，另外我认为除开原关键词的因素外，obsidian和哦不是的优先度应该同级才对。

**Comment by Newdea** [comment]
不是原本的，但用的时候有这样的问题，这里只是举个🌰
按你说的算法确实不应该有这样的问题，奇怪了。

最短路径，比如文件a我想移动到ob 文件夹下，但给出的建议希望是以下的顺序(目前不是的)
```
ob
ob/plugin
ob/plugin/sth1
ob/plugin/sth1/sth2
```

**Comment by lazyloong** [comment]
好了，我发现了我这逆天算法，按位置评分时是按的百分比，也就是同样是匹配第一个字，总共2个字的分数低于总共10个字的🙈，试试2.10.3版

**Comment by Newdea** [comment]
感谢,我下载试用了, 效果好了许多, 最短路径的已经在前面了👍🏻️
