### ISSUE TITLE
一个bug，和一个功能建议

### ISSUE THREAD

**Issue by FEI352** [lazyloong/obsidian-fuzzy-chinese#31]
1. 安卓平板，安卓13，小米平板5 Pro 5G，MIUI14使用的时候，输入框不出现光标。
![Screenshot_2023-12-22-11-28-26-652_md obsidian-edit](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/104716040/038f507b-4bab-49dd-801e-97fffaa7681e)
2. Fuzzy Chinese Pinyin: Execute Command是否能够增加顶置命令？这样我就能代替官方的命令面板了。

**Comment by lazyloong** [comment]
2.11.0版都解决了
