### ISSUE TITLE
是否能把 、作为 / 的一种模糊匹配

### ISSUE THREAD

**Issue by quanru** [lazyloong/obsidian-fuzzy-chinese#32]
因为中文输入下，二者是同一个键位

**Comment by lazyloong** [comment]
这个需求也太冷僻了一点吧，虽说这个插件就是为了不切中文就能搜索，但是如果把 、作为 / 的话，含有文件夹的搜索肯定会变得一团糟吧。

遇到符号直接跳过就行了，直接输下一个字或是空个格。

**Comment by quanru** [comment]
的确，直接使用空格替代 / 就挺好用了
