### ISSUE TITLE
多选文件时，支持同时移动多个文件

### ISSUE THREAD

**Issue by quanru** [lazyloong/obsidian-fuzzy-chinese#33]

**Comment by lazyloong** [comment]
OK了，请尝试2.12.0版

**Comment by quanru** [comment]
👍🏻，右键菜单可以啦，但是我用快捷键就不行

**Comment by lazyloong** [comment]
快捷键移动多个文件？原版也没有这个功能啊

**Comment by quanru** [comment]
原版有移动单个文件的功能
![image](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/11739753/78449f8c-49a7-428b-800e-95aa4252efaa)

**Comment by lazyloong** [comment]
噢，我以为你说的是文件列表多选然后快捷键移动。移动当前打开的文件确实是有，你是说红圈圈出的功能没有效果吗

**Comment by quanru** [comment]
对，选择多个文件时，通过快捷键仍然只会移动一个文件

**Comment by lazyloong** [comment]
就是说啊，确实是没有这样设计。这个命令对标的是原来的 `将文件移动到其他文件夹` 命令，只能移动当前打开的文件，原版也是这样的，不过我看看可不可以实现。

**Comment by lazyloong** [comment]
现在应该可以了，2.13.0

**Comment by quanru** [comment]
可以啦！🎉
老哥高效！
