### ISSUE TITLE
2.18.2 插件市场无法安装

### ISSUE THREAD

**Issue by LawyZheng** [lazyloong/obsidian-fuzzy-chinese#40]
<img width="406" alt="image" src="https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/26927551/bd5eb894-c74b-417d-8c85-37c846829724">

版本 2.18.2

其他插件安装没有问题，网络也是正常的。

**Comment by zhao414** [comment]
same issue here

OB v1.5.7

**Comment by wty21cn** [comment]
同样问题，看起来应该跟市场标记的版本是2.18.2，但是 github上的 release 版本是 2.18.3 有关

**Comment by zhao414** [comment]
> 同样问题，看起来应该跟市场标记的版本是2.18.2，但是 github上的 release 版本是 2.18.3 有关

能自己手动安装吗?

**Comment by lazyloong** [comment]
啊这，是我打错了版本号，现在已经搞好了🙈

**Comment by zhao414** [comment]
> 啊这，是我打错了版本号，现在已经搞好了🙈

👍已经可以安装了。thanks！
