### ISSUE TITLE
移动文件夹支持快捷键设置

### ISSUE THREAD

**Issue by quanru** [lazyloong/obsidian-fuzzy-chinese#41]

**Comment by lazyloong** [comment]
从文件列表选择文件夹之后使用 Move File 命令也可以移动，选择文件也可以，直接调用对应的快捷键就可以了。

**Comment by quanru** [comment]
选择文件可以，文件夹无法唤出命令
![image](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/11739753/914d4558-6247-4ff3-b918-8d422d92cfb1)

**Comment by lazyloong** [comment]
你要从文件列表中选择文件或文件夹啊，shift点击选择

**Comment by quanru** [comment]
学习了，原来要 shift

**Comment by lazyloong** [comment]
当然，同时选择多个可以一起移动

**Comment by quanru** [comment]
谢谢哥！
