### ISSUE TITLE
建议：新增激活文档不同级别标题的拼音搜索

### ISSUE THREAD

**Issue by feitian6186** [lazyloong/obsidian-fuzzy-chinese#43]
大佬：
      你好！建议新增对当前激活文档一级标题、二级标题等不同级别标题的拼音搜索。

**Comment by feitian6186** [comment]
是的，大佬 ，你说的命令就是我梦寐以求的功能，我已经找了好多天，找了好多插件。这个问题折磨我好多天。没想到大佬早就有先见之明，厉害，厉害，高见👍!膜拜！
如果大佬能在readme 文档中，补充了一下就更好了。我当初只看了readme文档，没有调出命令栏，仔细看。幸亏得到大佬提醒。

**Comment by lazyloong** [comment]
好吧，我总是加了新功能之后忘记改文档。
