### ISSUE TITLE
【建议】增加在新标签页打开文件的配置选项

### ISSUE THREAD

**Issue by feitian6186** [lazyloong/obsidian-fuzzy-chinese#45]
大佬，你好！

       通过拼音搜索到文件后，按下回车键，当前激活的文件会被覆盖。这有些不符合我的使用习惯。

       我希望搜索到文件后，按下回车键，搜索到的文件能以新的标签展示。

      如果要实现这个功能，按照软件目前的设置，我需要按下组合键（Ctrl+Enter）。有点麻烦。

      所以，建议大佬能不能新增“在新标签页打开文件”这个配置项，以满足不同用户的需求。

**Comment by lazyloong** [comment]
OK，可以到设置里配置快捷键了

**Comment by feitian6186** [comment]
大佬，真厉害。不但动作迅速、高效，而且给出的解决方案远远超出了我的预期。佩服、佩服。

**Comment by feitian6186** [comment]
大佬，能不能更进一步，搜索到文件以分屏的形式，在左侧或者右侧打开。

**Comment by lazyloong** [comment]
不是有了吗，新开个面板，或者在已经打开的面板中覆盖

**Comment by feitian6186** [comment]
大佬，你说的对。这么好的功能，我竟然没有发现。大佬 ，考虑得真周到。
