### ISSUE TITLE
 [FR]支持Aliases

### ISSUE THREAD

**Issue by Azona77** [lazyloong/obsidian-fuzzy-chinese#46]
- 一些条目包括中文标题和英文aliases，希望在搜索时两者能相通（平权）
  - 自带的快速切换是两者都能搜索到的
  - （不清楚Aliases这个特殊的属性有没有开放api）

**Comment by lazyloong** [comment]
你的意思是别名搜索不到吗，不应该啊，yaml区alias和aliases属性都可以搜索的，权重也是相等的

**Comment by Azona77** [comment]
> 你的意思是别名搜索不到吗，不应该啊，yaml区alias和aliases属性都可以搜索的，权重也是相等的

我发现问题所在了，我的Aliases属性是开头大写的
这在核心插件里是支持的，在这里需要小写才支持；那就不是什么问题了，我去vscode替换一波，感谢~

**Comment by lazyloong** [comment]
额，这样啊，那我去代码里改改就行了，既然核心插件是支持的，那我这个也应该支持

**Comment by lazyloong** [comment]
OK，已经修改了
