### ISSUE TITLE
【建议】 建议在每条记录后面加一个修饰符，提高访问文件的速度

### ISSUE THREAD

**Issue by feitian6186** [lazyloong/obsidian-fuzzy-chinese#47]
大佬，你好！
        通过拼音搜索，我可以很方便的找到我想要的文件。这点非常方便。不过，在切换之前的搜索文件时，我觉得可以再优化一些。

        在切换文件时，插件会弹出obsidian-fuzzy-chinese 窗口，此时窗口里会显示搜索到的历史文件列表，通过上下方向键可以选择文件。不过，这里有点小麻烦。如果待切换的文件位置在3行左右，还可以接受。如果待切换的文件位置在7行左右的话，就比较麻烦了，我需要多次移动方向键或者重新搜索。
       
       是否有更好的解决方案？

       我有个想法，是否可以在搜索到的每条记录后面加一个字母，通过leadkey+字母的方式快速访问。leadkey可以设置位为空格（推荐）或Alt，字母设置成asdfjklgh(推荐)或abcdefg。如果设置成推荐方案的话 ，可以减少手指的移动。具体如下图：

![PixPin_2024-04-22_17-30-39](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/42461871/3ddbaba0-27ff-484f-b5f6-12881bd51b87)
        
       期待大佬的回应！

**Comment by feitian6186** [comment]
修饰符有两种方式，一种是字母，一种是数字。

1. 如果使用字母的话，也有两种方式。
    （1）asdf（左手） jkl（右手）gh(中间)，即 asdfjklgh，总共10个字母。【推荐】
    （2） abcd....【不推荐】。这也是大佬持怀疑态度的方案。

2. 如果使用数字的话，最好使用上方的数字键，不推荐小键盘的数字键。我的pocker II（61键）没有数字键。笔记本也没有数字键。

另外，我有个问题：当输入字母或数字的时候，obsidian-fuzzy-chinese 如何区分是执行搜索命令还是选择历史记录呢？

我想到的方案是添加一个引导键（ leaderkey）。关于leaderkey ，我也想到了两种方案。
1. 空格+ 字母/数字：按下空格键，然后再按下对应的字母或数字，即可跳转到对应的文档。空格键和字母/数字有先后顺序。【推荐】
2. Ctrl/Alt+字母/数字：同时按下Ctrl/Alt+字母/数字。类似快捷键。

以上是我的想法，仅供参考。

**Comment by lazyloong** [comment]
噢，asdfgh啊，我看错了，如果是这样的话那还可以。引导键的话，不如做成配置快捷键的一个选项吧。

**Comment by lazyloong** [comment]
也不对啊，配置的快捷键只涉及回车键的功能，那还是固定用alt好了

**Comment by feitian6186** [comment]
大佬，引导键还是做成选项吧 。
键盘做了映射，Alt和Ctrl 键进行了对调使。如果用Alt+字母键的话，我实际按的是Ctrl+字母键，或者我使用Autohotkey脚本进行转换。两种情况对我来说 ，都比较麻烦。
对我来说，空间键+字母键是最方便的。

**Comment by lazyloong** [comment]
空格键最大的问题是怎么区别是要输入空格还是选择

**Comment by feitian6186** [comment]
如果第一个输入字符是空格，则进入选择状态。
否则，进入输入状态。
因为如果想搜索文件的话，第一个字符不可能是空格。

具体的流程是：
1. 搜索新文件流程：            弹出搜索对话框，输入首字母或拼音，进行文件搜索。
2. 搜索历史文件列表流程： 弹出搜索对话框，输入空格键+对应的字母键，进行历史文件选择。

**Comment by lazyloong** [comment]
啊？你只说选择历史文件啊，我还以为你要每个搜索的选择功能呢😂

**Comment by feitian6186** [comment]
大佬，你的做到插件实在太好用了。
我再提一个功能。能不能在Search Heading基础上，形成大纲功能(outline)呀。
输入大纲命令（outline），弹出类似Search Heading的界面，下方的内容以一级标题的形式收缩起来。
通过上下键可以上下移动，但是不展开。
如果想展开的话，可以使用方向右键展开 ，如果想折叠的话，可以使用方向左键折叠。
如果想一次性展开到二级标题的话，可以在上方的输入命令框中，输入空格+2。其他层级类似。如果想一次性展开，可以输入空格+7。如果想全部折叠的话，可以输入空格+1。
同时上面的搜索框依然保持与Search Heading一样的搜索标题的功能。

**Comment by lazyloong** [comment]
我觉得这些也太繁杂了吧，多了一些特意的操作，感觉有点冗余了。这个插件一开始是对标的原来的快速切换，搜索结果不应该搞这么多操作。

**Comment by lazyloong** [comment]
好了，在设置里打开选项就可以用空格加asdfgh或123456打开文件了

**Comment by feitian6186** [comment]
大佬，太厉害了 。能收到大佬的来信 ，是我今天最开心的事情。
不过 ，我在使用时，遇到了一点小麻烦。前几条记录，我可以直接使用组合键，但是后面的记录 ，我就不知道使用哪个字母或数字了。
如果每条记录后面都有对应的提示就好了。如下图：
![image](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/42461871/8039b87a-56bc-45ac-b296-72e85e067149)

期待大佬的再次优化！

**Comment by feitian6186** [comment]
同时，还建议gh，要放在jkl  后面，这样可以减少手指的移动。左手摆放的字母（asdf），右手摆放的字母（jkl）和中间的字母（gh）
即  asdf jkl gh ，总共9个。

**Comment by lazyloong** [comment]
好了

**Comment by feitian6186** [comment]
大佬 ，完美！又好又迅速。神一样的存在。哇~
