### ISSUE TITLE
【功能建议】增加忽略文件

### ISSUE THREAD

**Issue by wizardwen** [lazyloong/obsidian-fuzzy-chinese#48]
大佬，你好！
希望可以添加搜索时忽略的文件，有些文件不希望在搜索时显示出来。
类似于设置：文件与链接-忽略文件，插件可以使用系统设置项或自定义设置项。

可以使用拼音搜索很是方便，已经替换默认的搜索项了，多谢大佬。如果可以增加忽略文件，相信使用体验将会更好。

**Comment by lazyloong** [comment]
好了，用的是系统设置项
