### ISSUE TITLE
希望能支持全文搜索，类似omnisearch

### ISSUE THREAD

**Issue by qiangu2020** [lazyloong/obsidian-fuzzy-chinese#49]

**Comment by lazyloong** [comment]
为什么会想要用拼音搜索全文，拼音重码率那么高，在成千上万个笔记的库中，光是搜索标题就容易出现大量非目标结果了，从全文搜索的结果里找到想要的结果肯定更难，拼音搜索全文没有理由比直接搜索全文更有优势。
