### ISSUE TITLE
【功能建议】建议新增右键功能

### ISSUE THREAD

**Issue by feitian6186** [lazyloong/obsidian-fuzzy-chinese#50]
大佬 ：
        你好 ！ 
        利用大佬开发的插件可以很方便地搜索到需要的pdf文件。但是，obsidian 自带的pdf插件对我来说 ，不是很好用。我更希望利用okular这款软件打开pdf文件。因为该软件可以很方便的自定义快捷键，所以可以把上下键和翻页键定义成自己舒适的按键。
        我现在的解决方案是利用Quick Explorer 来定位到需要的文件，然后右键打开默认软件。这样 ，对我就比较麻烦了。我需要层层查找到文件，同时，也需要把文件夹和文件名都改成英文的，以方便英文定位。这两项都是比较大的工作。这不是我想看到的。
        我的想法是能不能把Quick Explorer 的右键菜单替换掉系统自带的菜单或者增加利用默认软件打开。因为系统自带的右键菜单只有复制、剪切、粘贴等简单功能。

![image](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/42461871/70cf48a7-393a-4720-82b5-09b5666bff27)
![image](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/42461871/fb5752c1-21ae-4f88-ada0-dff7f84ad6ae)

**Comment by lazyloong** [comment]
你的意思是右键点击文件搜索的结果时产生和右键点击双链一样的菜单吗

**Comment by feitian6186** [comment]
通过上下键移动到待处理的文件位置，按下键盘上的菜单键（Menu键），弹出类似Quick Explorer 的右键菜单或者右键点击双链弹出的菜单。如果选择右键点击双链弹出的菜单的话， 建议能精简一下。因为格式化（Format）、段落（Paragraph）和插入（Insert）等一些菜单是多余的。不过，不改也无妨。同时 ，也希望能保持Quick Explorer的按特定的字母跳转到具体的菜单项上的功能，比如我按下字母e，就能匹配到default，进而能跳转到 "Open in default app"这个菜单栏上。

注：据我使用多款软件的经验来说，我总结出选择菜单项有两种方式。
1. 通过上下方向键或者vim模式的jk 键来进行菜单的选择。优点是不用思考可以很自然的操作，缺点是如果菜单项多的话，需要多次移动。
2. 通过单个字母或者修饰符与具体菜单上的字母相匹配的模式来进行菜单的选择。优点是可以快速跳转，缺点是当有多个菜单项的话，单字母需要多次不同字母的尝试。不过，修饰符也不存在这个问题。两者都需要费点脑子。

**Comment by lazyloong** [comment]
额，我没找到取消原来的菜单的方法，这导致每次新加的双链菜单出现一下就消失，然后出现系统菜单

**Comment by feitian6186** [comment]
非常感谢大佬能抽时间来研究。
这是一个锦上添花的功能，其他软件已经实现了。
我只所以想让obsidian-fuzzy-chinese这款插件也能实现，是因为希望能给使用这款插件的用户进一步提升效率。
既然不好实现的话 ，就算了吧。
再次感谢！
