### ISSUE TITLE
【功能建议】新增一个只能浏览的菜单

### ISSUE THREAD

**Issue by feitian6186** [lazyloong/obsidian-fuzzy-chinese#51]
大佬：
        你好！
        还是非常希望能增加一个查看文章目录的功能。只需要2个功能就可以了。不需要和文章的内容联动。这样可以很方便的查看整篇文件的大纲结构，对文件的整体框架有个清晰的认识。具体需求如下：
        1. 展开目录层级。
            1. 按 a：展开一级目录
            2. 按 s：展开二级目录
            3. 按 d：展开三级目录
            4. 按 f： 展开四级目录
            5. 按g： 展开五级目录
            6. 按h： 展开六级目录
        2. 上下滚动。
            1. 按 j： 向下滚动
            2. 按 k：向上滚动 

       展示形式和查找文章标题的弹框一样，只把搜索框去除就可以了。
       
       这个功能非常希望能实现，虽然这和obsidian-fuzzy-chinese最初设定的快速切换文件目标有点不一致。

**Comment by lazyloong** [comment]
有一说一，我没看出来这个功能和拼音搜索有什么关系，也没有理由在这个插件里加上这个功能

**Comment by feitian6186** [comment]
大佬说的对~
从插件的独立性或者原子性来说，的确是为难拼音插件了。
大纲功能就应该是找大纲插件的Up主。其实 ，我也和 obsidian-quiet-outline 的Up主发聩了，但对方有好多问题（issues）要处理。
看到拼音插件搜索标题的界面和我想要的大纲功能界面有点相似，所以才提了一口。其实，我也知道不合适。 
不过，还是要谢过大佬的回复。

**Comment by lazyloong** [comment]
写了一个实现这个功能的插件，你试试看
链接: https://pan.baidu.com/s/1JJeJ7eOEuEvcojdkpGSckQ?pwd=1111 提取码: 1111

**Comment by feitian6186** [comment]
大佬 ，真牛，神一般的存在。真是喜出望外。太感谢了~
