### ISSUE TITLE
[Bug]: 快捷键Enter打开文件时会插入空行

### ISSUE THREAD

**Issue by hustrjh** [lazyloong/obsidian-fuzzy-chinese#52]
## 问题
使用快捷键Enter打开文件时有bug，会在文档中异常插入空行。

## 现象
在Sandbox库中测试，仅安装了Fuzzy Chinese Pinyin插件，具体见下图：
![Enter](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/69783980/f3b2a1eb-6224-4a56-981f-0c012907bda5)

**Comment by lazyloong** [comment]
OK了，请更新至2.22.2版

**Comment by hustrjh** [comment]
太棒啦！感谢！👍
