### ISSUE TITLE
[新功能]可不可以加入模糊音搜索功能。

### ISSUE THREAD

**Issue by jiapeng123456** [lazyloong/obsidian-fuzzy-chinese#53]
可不可以加入模糊音搜索功能。例如：s -> sh。
对于平翘舌不分的人十分有帮助。

**Comment by lazyloong** [comment]
好了，请更新至2.23.0版，在设置里打开选项之后记得再配置一下方案
模糊音根据这个表写的
![image](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/54649691/c18bb0ba-b5c5-45c9-b5df-3fafdcb084ea)
