### ISSUE TITLE
Ob 1.6.4 插入标题失效

### ISSUE THREAD

**Issue by zhao414** [lazyloong/obsidian-fuzzy-chinese#56]
在笔记中输入[[noteName#header]]的方式，能够弹出推荐菜单，也能看到各个header，但是不论用鼠标点击还是键盘选中后按回车，相应的header都不能插入。

Ob 1.6.3无此问题。

目前通过回滚到Ob 1.6.3来用。

请看看怎么回事。

**Comment by lazyloong** [comment]
可是 Ob 1.6.4 还没有公开呢，我没办法用 Ob 1.6.4 debug

**Comment by zhao414** [comment]
。。。好吧

我觉得可能是 1.6.4的这个修复：Fixed link autocompletion for headings (via [[#) sometimes generating invalid links.

**Comment by zhao414** [comment]
这是console的报错信息

**Comment by zhao414** [comment]
好像我不能传图片。。。。

**Comment by zhao414** [comment]
比如我想引用[[note#abc]]

我对比了一下，OB 1.6.4 自带的插入header的功能，调用了selectSuggestion，并且送进去的参数对象中，subpath属性是“#abc”，而我看到在目前插件送进去的参数对象的subpath属性是“#”

**Comment by zhao414** [comment]
我把：
[obsidian-fuzzy-chinese](https://github.com/lazyloong/obsidian-fuzzy-chinese/tree/main)/[src](https://github.com/lazyloong/obsidian-fuzzy-chinese/tree/main/src)/[editorSuggest](https://github.com/lazyloong/obsidian-fuzzy-chinese/tree/main/src/editorSuggest)
/fileEditorSuggest.ts

line 189

`subpath: "#",`

改成了

`subpath: isLinkItem(item) ? "#"+item.link : "#"+item.name,`

就可以了。

目前我电脑上好像没有安装编译环境。没法编译。我通过直接改js的方法，测试过了，对于header，这个方法奏效。
