### ISSUE TITLE
移动文件功能不能新建文件夹

### ISSUE THREAD

**Issue by Tback1** [lazyloong/obsidian-fuzzy-chinese#59]
使用obsidian自带的移动移动时，填入路径例如 `1\2\` 按下 `Shift+Enter` 能够从 `root` 目录下新建文件夹
但使用fuzzy的移动命令时，`Shift+Enter` 命令失效。

更进一步，在使用 首字母取到某个路径 tab补全后 在之后填入 `\新文件夹名\` 亦是无效的。

盼望修复这个问题

**Comment by lazyloong** [comment]
试试 2.27.1 版有没有问题

**Comment by Tback1** [comment]
在 2.27.2 版本修复好了 非常感谢 🎉🎉🎉🎉
