### ISSUE TITLE
可以考虑加入基于双拼的查找功能

### ISSUE THREAD

**Issue by zhcqiu** [lazyloong/obsidian-fuzzy-chinese#6]
除了使用全拼，还有不少人习惯于双拼。在不同的双拼方案下，首字母会有不同，开发者可以考虑加入常用的双拼方案，如小鹤双拼，微软双拼等等。
应该不会很麻烦，可以增加几个dict；或者通过正则表达式，在全拼和双拼之间建立映射关系。不同的方案，可在option中给使用者选择。
如果能够实现，将十分感谢！

**Comment by lazyloong** [comment]
这确实是个很实用的功能，只需要将原来的拼音到汉字映射表中的全拼拼音按对应关系转换为双拼拼音，不过要等考完试了。

搜狗输入法列出来的双拼怎么样，够全面了吗，映射表都不需要搜了
![image](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/54649691/e1905565-544c-4205-9112-c501c1ae9cc2)

**Comment by lazyloong** [comment]
2.2.0版添加了双拼功能，但是双拼方案太多了，暂时只添加了智能ABC、微软双拼、小鹤双拼

**Comment by zhcqiu** [comment]
谢谢，我试了一下，挺好的，多谢了！
常用的双拼方案就是那些了吧，其他的太小众了。
