### ISSUE TITLE
Ob 1.7.4 移动文件命令有时候加载不起来

### ISSUE THREAD

**Issue by Tback1** [lazyloong/obsidian-fuzzy-chinese#63]
移动文件命令有时候加载不起来, 现象是 `右键菜单`、`命令面板`、`快捷键面板` 都找不到fuzzy 的移动文件命令。但其他4个命令正常。预设的快捷键也无效
![image](https://github.com/user-attachments/assets/2a4f8182-15e4-471d-b983-47ed90091d02)
![image](https://github.com/user-attachments/assets/13831a67-f773-475a-990f-c12027a042cf)

这个问题时不时出现，复现不能百分之百保证。刚刚更新到1.7.4后测试了半个小时，确定是有这个问题

看了一下官方通告，怀疑是官方更新带来的一些改变造成的

在 1.7.2 的更新指南里 有写到 https://forum-zh.obsidian.md/t/topic/40384
> 一些视图现在仅在打开时才加载，这将提高启动性能和内存使用率。但这可能会导致一些插件出现问题，插件开发者可根据我们[发布的指南](https://docs.obsidian.md/Plugins/Guides/Understanding+deferred+views) 对插件进行升级。

**Comment by lazyloong** [comment]
确实是因为文件树视图的延迟加载导致的，现在在2.27.4版里修复了

**Comment by Tback1** [comment]
辛苦了，不过OB1.7.4现在真是问题多多，卡顿太厉害了，暂时我还是回退到1.6时代了。
