### ISSUE TITLE
[功能请求]优化标签搜索「tags是占位符的模板」不能正常使用的问题。

### ISSUE THREAD

**Issue by YanCore** [lazyloong/obsidian-fuzzy-chinese#66]
这个问题应该比较容易解决，希望早点修复。最简单的方式，只处理数组、字符串类型的tags。

## 复现方式
1. 新建一个模板 tags字段是{{}}的模板。
![image](https://github.com/user-attachments/assets/7c1229e8-9fa4-48a2-b342-84a03dbb0e50)

2. 使用标签搜索任意标签。
![image](https://github.com/user-attachments/assets/e8f807d6-fd1c-4988-b1fe-25d4e5819803)

## 日志
![image](https://github.com/user-attachments/assets/e6006738-03d2-4aee-8505-d99852e7927d)

**Comment by YanCore** [comment]
我在原有的基础上修改一行代码，可以成功搜索。

```javascript
tagArray = Array.isArray(tags) ? tags : (typeof tags === 'string' ? tags.split(",").filter((p) => p).map((p) => p.trim()) : []);
```

```javascript
function getFileTagArray(file) {
  var _a, _b, _c, _d;
  let tags = ((_b = (_a = app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter) == null ? void 0 : _b.tags) || ((_d = (_c = app.metadataCache.getFileCache(file)) == null ? void 0 : _c.frontmatter) == null ? void 0 : _d.tag), tagArray;
  if (tags)
    tagArray = Array.isArray(tags) ? tags : (typeof tags === 'string' ? tags.split(",").filter((p) => p).map((p) => p.trim()) : []);
  return tagArray;
}
```

**Comment by YanCore** [comment]
顺带一提，有点不清楚getFileTagArray函数里面下面这行代码tags、tagArray的关系。
```javascrapt
  let tags = ((_b = (_a = app.metadataCache.getFileCache(file)) == null ? void 0 : _a.frontmatter) == null ? void 0 : _b.tags) || ((_d = (_c = app.metadataCache.getFileCache(file)) == null ? void 0 : _c.frontmatter) == null ? void 0 : _d.tag), tagArray;
```
是BUG吗？
```javascrapt
let tags = "两个判断得到一个布尔值",tagArray;
```

提到这个，是因为我得到的搜索结果是「关键词和标签的并集」，而不是我想要的「关键词和标签的交集」，我刚开始使用这插件，不确定是不是正确的逻辑。

![image](https://github.com/user-attachments/assets/d3596022-b24a-4646-99c3-d0f8582fd997)

**Comment by lazyloong** [comment]
tags是得到的原始数据，可能是字符串，也可能是数组
```
// 得到数组
tags:
  - a
  - b

// 得到字符串
tags: a, b
```
要统一处理成数组的形式方便后续使用，就是tagArray

但是你今天给我开了眼了，`tags: {{abc}}` 竟然是个对象😂
![image](https://github.com/user-attachments/assets/ba9363f7-8212-462f-9ff5-836e8cc21cd0)
也就是 ob 认为正确的形式是这样的是这样的 `tags: { "{abc}":"a" }`，后面没有值所以是 null

貌似 ob 没有加入对象里的东西，我干脆判断是对象就跳过了

**Comment by lazyloong** [comment]
哦，关于交并集的部分确实写错了，都在 2.27.7 版里改了
