### ISSUE TITLE
「BUG」[[]]使用模糊拼音搜索时不能通过输入#和^进一步搜索选中文件内的块和章节

### ISSUE THREAD

**Issue by Xianyu39** [lazyloong/obsidian-fuzzy-chinese#68]
这是正常的情况：
![PixPin_2024-11-15_10-27-02](https://github.com/user-attachments/assets/f085c5ee-ecea-4317-9e38-e7d908e05719)
这是使用模糊拼音之后导致的情况：
![PixPin_2024-11-15_10-29-08](https://github.com/user-attachments/assets/3b78861c-d119-451f-aa08-f30980d1fe16)

**Comment by lazyloong** [comment]
当那个“图神经网络”的笔记弹出来的时候，你真的没有按回车确定的冲动吗🤔
从逻辑上来讲，“tu神经网络”并不能完全指代“图神经网络”吧，也可能是其他名字包含“图神经网络”的笔记，所以查询标题名当然是查不到的

**Comment by lazyloong** [comment]
不过看了你的演示，我发现好像对markdown链接的支持有问题，晚点修复一下

**Comment by Xianyu39** [comment]
我要引用的不是「图神经网络」整个文件，而是「图神经网络」中那一个叫做「介绍」的章节（因为这篇文章只有一个章节，可能给你造成了误导）。以往的话只需要输入一部分，列表中选中想要的文件，再输入#就可以转到搜索文件内的章节标题；输入^就可以转到搜索文件内的块。现在问题是经过模糊拼音之后搜索#就不会转到搜索文件内的章节了。

**Comment by lazyloong** [comment]
主要就是你用标准md链接，但是我向来喜欢用wiki链接，就没发现这个问题，按wiki链接的正常习惯就这样，很丝滑
![bandicam 2024-11-15 12-23-30-543](https://github.com/user-attachments/assets/12b2e411-b4b6-4af5-920c-0759a54c0240)
但是如果用标准md链接，一tab就变成了`[图神经网络](图神经网络.md)`，而无论是ob原生的插件还是我的插件，都不对标准md链接进行块和标题搜索

**Comment by lazyloong** [comment]
我得想想怎么操作才方便标准md链接输入

**Comment by lazyloong** [comment]
试试2.27.10版，用tab先选择了文件再输入章节
