### ISSUE TITLE
[Feature Request] 在输入[[的时候文件连接能支持中文拼音搜索的功能吗

### ISSUE THREAD

**Issue by LazyCountry** [lazyloong/obsidian-fuzzy-chinese#7]

**Comment by LazyCountry** [comment]
测试了下，确实可以，感谢

**Comment by LazyCountry** [comment]
如果是先输入 【【， 然后obsidian会自动替换为 [[ 但是没有自动加上 ]]， 这个时候没有办法按回车输入链接

**Comment by lazyloong** [comment]
现在试试呢

**Comment by LazyCountry** [comment]
输入 【【 是可以完成链接，但是链接的地址在是别名的时候是错的。
![image](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/2960008/ca1cf3e4-43d2-4a14-8787-d0050f5bc0a5)
![image](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/2960008/5b4fc35e-904c-4a02-9a8e-3773b19a1d83)

**Comment by lazyloong** [comment]
好吧，确实粗心大意了一点，这个问题也解决了

**Comment by LazyCountry** [comment]
测了下，修复了，感谢。暂时没有遇到问题了。
