### ISSUE TITLE
无法创建笔记

### ISSUE THREAD

**Issue by bailob** [lazyloong/obsidian-fuzzy-chinese#70]
1. 在 fuzzy-chinese 中键入不存在的笔记名并回车，无法创建笔记

2. 定义了wikilink，已赋予名称但尚未建立的笔记。使用默认的quick switch可以搜索到并回车创建，但是用 fuzzy-chinese 可以搜索到，但回车无效果。

3. 在canvas中点击或拖拽笔记图标，会弹出  fuzzy-chinese，但无法新建笔记

Obsidian 版本 1.7.7 ，用新仓库测试问题同样存在

**Comment by lazyloong** [comment]
请尝试一下2.27.11版

**Comment by bailob** [comment]
2.27.11 版本直接呼出的“搜索文件”功能可以正常创建新文件。但是canvas点击note图标调用的“搜索文件”功能仍无法正常创建新文件，并且创建失败后，直接呼出“搜索文件”也不能正常创建了，要 force reload 才能恢复
