### ISSUE TITLE
canvas点击note图标调用的“搜索文件”功能仍无法正常创建新文件

### ISSUE THREAD

**Issue by bailob** [lazyloong/obsidian-fuzzy-chinese#71]
2.27.11 版本直接呼出的“搜索文件”功能可以正常创建新文件。但是canvas点击note图标调用的“搜索文件”功能仍无法正常创建新文件，并且创建失败后，直接呼出“搜索文件”也不能正常创建了，要 force reload 才能恢复

_Originally posted by @bailob in https://github.com/lazyloong/obsidian-fuzzy-chinese/issues/70#issuecomment-2522757609_

**Comment by lazyloong** [comment]
噢噢，不好意思，之前改好了忘记推上来了，2.27.12版应该没问题了

**Comment by bailob** [comment]
2.27.12 所有功能都正常了
