### ISSUE TITLE
[BUG] 双链建议无法显示未创建的笔记

### ISSUE THREAD

**Issue by Shigo-45** [lazyloong/obsidian-fuzzy-chinese#72]
在官方提供的链接功能中，即便是未创建的笔记，只要在其他地方链接过也能在建议框中显示：
![截屏2024-12-13 17 00 25](https://github.com/user-attachments/assets/decd2ba2-caaa-42b6-b1ad-36650b7dc107)

但如果打开了插件的“使用双链建议”功能，无论是使用汉字还是拼音都无法搜索到未创建的笔记了：
![截屏2024-12-13 17 00 52](https://github.com/user-attachments/assets/ae1c3f38-a956-4327-8a94-62e15aeaa88b)
![截屏2024-12-13 17 01 21](https://github.com/user-attachments/assets/d5bfe655-53bc-4e1d-aa08-6d85b303cb81)

请问能否增加上述功能，感谢！

**Comment by lazyloong** [comment]
![image](https://github.com/user-attachments/assets/7571a4ec-c083-439e-9f83-fa13f6a44b9e)

你好，这个选项打开了吗，打开之后右边显示带加号的图标就是未创建的链接了

![image](https://github.com/user-attachments/assets/a3b108cf-1767-48d2-970f-9561d37720b4)

**Comment by Shigo-45** [comment]
> 你好，这个选项打开了吗，打开之后右边显示带加号的图标就是未创建的链接了


我在主力的库中打开过这个选项，但这会让建议功能完全失效（即便是已创建的笔记也无法建议）：
![截屏2024-12-13 17 29 41](https://github.com/user-attachments/assets/7421270f-3d9c-4b5c-8df3-620ce556824e)

但我在新建的库中测试了一下是可行的，或许是因为主力库的文件太多了（8000左右，如果算上未创建的笔记应该超过一万了）？
<img width="577" alt="截屏2024-12-13 17 40 12" src="https://github.com/user-attachments/assets/030ce19f-6c74-4288-a217-1aedad566564" />

测试了在主力库中关闭其他插件，同样无法显示:(

**Comment by lazyloong** [comment]
这个问题有点麻烦呢，我这里完全复现不出来，也许真是文件太多了，你的控制台里有报错吗，或者在控制台里输入 `app.plugins.plugins['fuzzy-chinese-pinyin'].fileModal.index.items.length` 看看到底有多少条链接，分别在打开和关闭那个选项的情况下运行一次。

![image](https://github.com/user-attachments/assets/16a12341-b3b2-4515-b4fa-6ed5c3a85d9b)

**Comment by Shigo-45** [comment]
未打开和打开的情况下的链接数分别为8699和13020

在打开“显示未完成链接”选项后进行文件搜索，有以下报错：
```
Uncaught TypeError: Cannot read properties of undefined (reading 'pinyin')
    at G.matchAboveStart (plugin:fuzzy-chinese-pinyin:21:13231)
    at G.match_ (plugin:fuzzy-chinese-pinyin:21:12857)
    at G.match (plugin:fuzzy-chinese-pinyin:21:12578)
    at Fr.getSuggestions (plugin:fuzzy-chinese-pinyin:21:44626)
    at t.updateSuggestions (app.js:1:1760215)
    at t.onInput (app.js:1:1760114)
```

在打开“显示未完成链接”选项后进行双链建议，有以下报错：
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'pinyin')
    at G.matchAboveStart (plugin:fuzzy-chinese-pinyin:21:13231)
    at G.match_ (plugin:fuzzy-chinese-pinyin:21:12857)
    at G.match (plugin:fuzzy-chinese-pinyin:21:12578)
    at Fr.getSuggestions (plugin:fuzzy-chinese-pinyin:21:44626)
    at Nr.getSuggestions (plugin:fuzzy-chinese-pinyin:21:62874)
    at t.trigger (app.js:1:1436437)
    at e.trigger (app.js:1:2042268)
    at app.js:1:1624628
    at l (app.js:1:518105)
    at c (app.js:1:518221)
```

**Comment by lazyloong** [comment]
现在用最新版试试呢，不过这只是跳过了出错的条目，如果控制台有什么输出的内容，请展开截个图

**Comment by Shigo-45** [comment]
可以正常检索到未创建的笔记了，谢谢！

在双链建议和文件搜索中用全拼检索“测试链接1”时，均有以下的连续输出：

![截屏2024-12-16 19 15 18](https://github.com/user-attachments/assets/8a297157-acd8-4a80-b280-c603eb771626)

**Comment by Shigo-45** [comment]
我也，感谢İlayda女士（不知何时才需要创建这个条目）😅
