### ISSUE TITLE
[Feature Request] 能否考虑新增一条命令支持搜索命令？

### ISSUE THREAD

**Issue by Yzzzzzzzzzzzz** [lazyloong/obsidian-fuzzy-chinese#8]

**Comment by lazyloong** [comment]
2.3.0版可以搜索命令和文件夹了

**Comment by bennyyip** [comment]
![image](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/7467687/a45021e9-1d3d-470d-9520-c98163f3fbda)
原版command palette会在右边显示命令的热键，有没有计划支持？

**Comment by bennyyip** [comment]
obsidian-better-command-palette 和 vscode 都会把最后执行过的几条命令置顶，挺实用的，可以考虑支持。
参考代码：
https://github.com/AlexBieg/obsidian-better-command-palette/blob/master/src/utils/suggest-modal-adapter.ts#L106C15-L106C15

**Comment by lazyloong** [comment]
显示热键这个是有计划的，就是太懒了先把搜索做出来先，不过既然有人提了干脆就做了

**Comment by bennyyip** [comment]
> obsidian-better-command-palette 和 vscode 都会把最后执行过的几条命令置顶，挺实用的，可以考虑支持。 参考代码： [AlexBieg/obsidian-better-command-palette@`master`/src/utils/suggest-modal-adapter.ts#L106C15-L106C15](https://github.com/AlexBieg/obsidian-better-command-palette/blob/master/src/utils/suggest-modal-adapter.ts?rgh-link-date=2023-08-20T23%3A23%3A54Z#L106C15-L106C15)

@lazyloong 这个也顺便做下吧，很简单

**Comment by lazyloong** [comment]
> > obsidian-better-command-palette 和 vscode 都会把最后执行过的几条命令置顶，挺实用的，可以考虑支持。 参考代码： [AlexBieg/obsidian-better-command-palette@`master`/src/utils/suggest-modal-adapter.ts#L106C15-L106C15](https://github.com/AlexBieg/obsidian-better-command-palette/blob/master/src/utils/suggest-modal-adapter.ts?rgh-link-date=2023-08-20T23%3A23%3A54Z#L106C15-L106C15)
> 
> @lazyloong 这个也顺便做下吧，很简单

已经加上了，把 ctrl np 做完就push

**Comment by bennyyip** [comment]
![image](https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/7467687/540da06b-dd5d-4717-a1f3-aec0c0bd3f76)
历史命令没有去重，改成Set吧，会保证顺序的
> You can iterate through the elements of a set in insertion order. The insertion order corresponds to the order in which each element was inserted into the set by the [add()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/add) method successfully (that is, there wasn't an identical element already in the set when add() was called).

另外 ctrl np 反了。n=next=下一个,p=previous=上一个

**Comment by lazyloong** [comment]
@bennyyip OK了🙈

**Comment by bennyyip** [comment]
@lazyloong 牛的
用了一下，有一个之前没想到的问题。如果一个命令已经在history里，再执行一遍不会变成第一个。
插入以前先把命令在history去掉再add吧。

**Comment by lazyloong** [comment]
@bennyyip 淦，不如使用带去重的数组得了

**Comment by bennyyip** [comment]
O(1) 变 O(n) 了…… 不过规模小没什么所谓

**Comment by lazyloong** [comment]
@bennyyip 这才几个元素啊，一次启动能运行几百几千次命令吗，O(n2)都没所谓

**Comment by bennyyip** [comment]
是啊，我也說了無所謂的
