### ISSUE TITLE
[无法使用] 最新版本ob安装最新版本插件使用报错

### ISSUE THREAD

**Issue by eryajf** [lazyloong/obsidian-fuzzy-chinese#9]
ob版本：v1.3.7
插件版本：2.2.0

启动插件时，ob控制台报错如下：

<img width="563" alt="image" src="https://github.com/lazyloong/obsidian-fuzzy-chinese/assets/33259379/76fa2c1e-ab00-487c-9a68-8e426dd2b945">

**Comment by lazyloong** [comment]
请问你是否存在用 `- ` 接纯数字的别名，比如
```
alias: 
- 1234
```

**Comment by eryajf** [comment]
应该是没有的，我把ob重启了，目前貌似能正常使用了。

**Comment by lazyloong** [comment]
好吧，不过奇怪的是通过你的提示，我确实找到了一个可以复现出一样报错的bug
